import type {
  Brief,
  Hypothesis,
  QuestionWithVariants,
} from "@/lib/rag/types";

export type ExportInput = {
  brief: Brief;
  hypotheses: Hypothesis[];
  questions: QuestionWithVariants[];
};

export type ExportFormat = "markdown" | "qualtrics" | "plaintext";

const VARIANT_LABEL: Record<string, string> = {
  neutral_direct: "Neutral direct",
  leading: "Leading",
  projective: "Projective",
  behavioural: "Behavioural",
  attitudinal: "Attitudinal",
  forced_choice: "Forced choice",
  constant_sum: "Constant sum",
  maxdiff: "MaxDiff",
};

function acceptedReadyQuestions(input: ExportInput): QuestionWithVariants[] {
  return input.questions.filter(
    (q) => q.status === "accepted" && q.selected_variant_id !== null,
  );
}

export function exportMarkdown(input: ExportInput): string {
  const accepted = acceptedReadyQuestions(input);
  const hypothesisById = new Map(input.hypotheses.map((h) => [h.id, h]));

  const lines: string[] = [];
  lines.push(`# Questionnaire — ${input.brief.title ?? "Untitled brief"}`);
  lines.push("");
  lines.push(
    `> Generated by Premise on ${new Date().toISOString().slice(0, 10)}. ${accepted.length} accepted question(s) with selected variant(s).`,
  );
  lines.push("");
  lines.push("## Brief");
  lines.push("");
  lines.push(input.brief.content);
  lines.push("");
  lines.push("## Questionnaire");
  lines.push("");

  if (accepted.length === 0) {
    lines.push(
      "_No accepted questions with a selected variant yet. Accept questions and pick a variant in the Premise canvas, then re-export._",
    );
    return lines.join("\n");
  }

  accepted.forEach((q, i) => {
    const variant = q.variants.find((v) => v.id === q.selected_variant_id);
    if (!variant) return;
    const hypothesis = q.hypothesis_id
      ? hypothesisById.get(q.hypothesis_id)
      : undefined;

    lines.push(`### Q${i + 1}. ${q.target_construct}`);
    lines.push("");
    if (hypothesis) {
      lines.push(`*Tests hypothesis:* ${hypothesis.statement}`);
      lines.push("");
    }
    if (q.rationale) {
      lines.push(`*Rationale:* ${q.rationale}`);
      lines.push("");
    }
    lines.push(`**${variant.statement}**`);
    lines.push("");
    if (variant.response_format) {
      lines.push(`*Response format:* ${variant.response_format}`);
    }
    if (variant.response_options.length > 0) {
      lines.push("");
      variant.response_options.forEach((opt) => lines.push(`- ${opt}`));
    }
    lines.push("");
    const label = VARIANT_LABEL[variant.variant_type] ?? variant.variant_type;
    lines.push(`*Variant chosen:* ${label}`);
    if (variant.what_it_elicits) {
      lines.push(`*Why this variant:* ${variant.what_it_elicits}`);
    }
    if (variant.caveat) {
      lines.push(`*Caveat:* ${variant.caveat}`);
    }
    lines.push("");
    lines.push("---");
    lines.push("");
  });

  return lines.join("\n");
}

export function exportQualtrics(input: ExportInput): string {
  const accepted = acceptedReadyQuestions(input);
  if (accepted.length === 0) {
    return "(no accepted questions with a selected variant yet)";
  }

  const lines: string[] = [];
  lines.push("[[AdvancedFormat]]");
  lines.push("");

  accepted.forEach((q, i) => {
    const variant = q.variants.find((v) => v.id === q.selected_variant_id);
    if (!variant) return;

    lines.push(`[[Question:${variant.response_options.length > 0 ? "MC:SingleAnswer" : "TE:Essay"}]]`);
    lines.push(`Q${i + 1}. ${variant.statement}`);
    lines.push("");

    if (variant.response_options.length > 0) {
      lines.push("[[Choices]]");
      variant.response_options.forEach((opt) => lines.push(opt));
    }
    lines.push("");
    lines.push("[[PageBreak]]");
    lines.push("");
  });

  return lines.join("\n");
}

export function exportPlaintext(input: ExportInput): string {
  const accepted = acceptedReadyQuestions(input);
  if (accepted.length === 0) {
    return "(no accepted questions with a selected variant yet)";
  }

  const lines: string[] = [];
  accepted.forEach((q, i) => {
    const variant = q.variants.find((v) => v.id === q.selected_variant_id);
    if (!variant) return;

    lines.push(`Q${i + 1}. ${variant.statement}`);
    if (variant.response_options.length > 0) {
      variant.response_options.forEach((opt) => lines.push(`  - ${opt}`));
    } else if (variant.response_format) {
      lines.push(`  (${variant.response_format})`);
    }
    lines.push("");
  });

  return lines.join("\n");
}

export function exportQuestionnaire(
  input: ExportInput,
  format: ExportFormat,
): { content: string; mime: string; filename: string } {
  const slug = (input.brief.title ?? "questionnaire")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  switch (format) {
    case "markdown":
      return {
        content: exportMarkdown(input),
        mime: "text/markdown",
        filename: `${slug}.md`,
      };
    case "qualtrics":
      return {
        content: exportQualtrics(input),
        mime: "text/plain",
        filename: `${slug}-qualtrics.txt`,
      };
    case "plaintext":
      return {
        content: exportPlaintext(input),
        mime: "text/plain",
        filename: `${slug}.txt`,
      };
  }
}
